version: "3.8"

services:
  db:
    build:
      context: './db/'
    restart: always
    container_name: "librino-db"

  backend:
    build:
      context: './backend/'
    depends_on:
      - db
    restart: always
    container_name: "librino-backend"

  frontend:
    build:
      context: './frontend/'
    ports:
      - 80:80
    depends_on:
      - db
      - backend
    restart: always
    container_name: "librino-frontend"
