version: '3.8'
services:
  postgres:
    container_name: "postgres"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=matteo
      - POSTGRES_PASSWORD=supersecurepass
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
